lvms:
  volumeGroup: vgdatamesh

rbac:
  name: lvms
  namespace: openshift-storage
  roles:
    - createRole: true
      resources:
        - storageclasses
      scope:
        cluster: true
      apiGroups:
        - "storage.k8s.io/v1"
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
