apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: datamesh-lvm
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: vgdatamesh
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
